x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  # 🟦 App Database
  app-db:
    image: postgres:16
    container_name: leetcode_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    <<: *default-logging

  # 🟥 Judge0 DB
  judge0-db:
    image: postgres:16.2
    container_name: judge0_database
    env_file: judge0.conf
    volumes:
      - judge0_db_data:/var/lib/postgresql/data
    restart: always
    <<: *default-logging

  # 🟨 Redis
  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always
    <<: *default-logging

  # ⚙️ Judge0 API
  judge0-server:
    image: judge0/judge0:1.13.1
    depends_on:
      - judge0-db
      - redis
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    <<: *default-logging

  # ⚙️ Judge0 Workers
  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    depends_on:
      - judge0-db
      - redis
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    <<: *default-logging

  # 🟩 App
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NODE_ENV: production
    container_name: leetcode_app
    depends_on:
      app-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    <<: *default-logging

  # 🔵 Prisma Studio
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      app-db:
        condition: service_healthy
    ports:
      - "5555:5555"
    restart: unless-stopped
    <<: *default-logging

volumes:
  app_db_data:
  judge0_db_data: