import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/provider/query-provider";
import { CircleX } from "lucide-react";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { useSession } from "@/modules/auth/hooks/useSession";
import AuthLayer from "@/modules/auth/components/auth-layer";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    useSession();
    return (
        <html
            lang="en"
            className={cn("font-sans", geist.variable)}
            suppressHydrationWarning
        >
            <body className={`${inter} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <QueryProvider>
                        <AuthLayer>{children}</AuthLayer>
                    </QueryProvider>
                </ThemeProvider>
                <Toaster
                    icons={{
                        error: <CircleX color="#ff0000" />,
                    }}
                />
            </body>
        </html>
    );
}
