import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/provider/query-provider";
import { CircleX } from "lucide-react";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={cn("font-sans", geist.variable)}>
          <body className={`${inter} antialiased`}>
              <QueryProvider>{children}</QueryProvider>
              <Toaster
                  icons={{
                      error: <CircleX color="#ff0000" />,
                  }}
              />
          </body>
      </html>
  );
}
